# Конфигурация логгера
logger:
  path: "logs/calendar-logs.log"
  level: "debug"

# Конфигурация сервера
server:
  grpc:
    host: 0.0.0.0
    port: 8081
  rest:
    host: 0.0.0.0
    port: 8080

# Данные базы данных
database:
  source: "postgres"
  user: "postgres"
  pass: "password"
  host: "pg-db"
  port: 5432
  database: "postgres"
  timeout: "60s"