# Конфигурация логгера
logger:
  path: "logs/logs.log"
  level: "debug"

# Конфигурация сервера
server:
  grpc:
    host: "localhost"
    port: 8081
  rest:
    host: "localhost"
    port: 8080

# Данные базы данных
database:
  source: "inmemory"
  user: "postgres"
  pass: "password"
  host: "localhost"
  port: 5432
  database: "postgres"
  timeout: "60s"