# Конфигурация логгера
logger:
  path: "logs/scheduler-logs.log"
  level: "debug"

# Конфигурация планировщика
scheduler:
  pause: "10s"

# Конфигурация сервера
server:
  grpc:
    host: "calendar"
    port: "8081"

# Конфигурация очереди
rabbit:
  host: "rabbitmq"
  port: "5672"
  exchange: "calendar-exchange-events"
  queue: "calendar-queue-events"
  key: "events"
  credential:
    username: "guest"
    password: "guest"
