// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/CalendarService.proto

package calendar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{2}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{3}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type ReadRequest struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Condition            int32                `protobuf:"varint,2,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{6}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ReadRequest) GetCondition() int32 {
	if m != nil {
		return m.Condition
	}
	return 0
}

type ReadResult struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResult) Reset()         { *m = ReadResult{} }
func (m *ReadResult) String() string { return proto.CompactTextString(m) }
func (*ReadResult) ProtoMessage()    {}
func (*ReadResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{7}
}

func (m *ReadResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResult.Unmarshal(m, b)
}
func (m *ReadResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResult.Marshal(b, m, deterministic)
}
func (m *ReadResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResult.Merge(m, src)
}
func (m *ReadResult) XXX_Size() int {
	return xxx_messageInfo_ReadResult.Size(m)
}
func (m *ReadResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResult proto.InternalMessageInfo

func (m *ReadResult) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int32                `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	DateEnd              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=date_end,json=dateEnd,proto3" json:"date_end,omitempty"`
	DateNotification     *timestamp.Timestamp `protobuf:"bytes,6,opt,name=date_notification,json=dateNotification,proto3" json:"date_notification,omitempty"`
	Description          string               `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{8}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Event) GetDateEnd() *timestamp.Timestamp {
	if m != nil {
		return m.DateEnd
	}
	return nil
}

func (m *Event) GetDateNotification() *timestamp.Timestamp {
	if m != nil {
		return m.DateNotification
	}
	return nil
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Notification struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int32                `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf653d2ee8347a4b, []int{9}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notification) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "event.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "event.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "event.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "event.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "event.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "event.DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "event.ReadRequest")
	proto.RegisterType((*ReadResult)(nil), "event.ReadResult")
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*Notification)(nil), "event.Notification")
}

func init() { proto.RegisterFile("proto/CalendarService.proto", fileDescriptor_cf653d2ee8347a4b) }

var fileDescriptor_cf653d2ee8347a4b = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x95, 0x6d, 0xb3, 0xbb, 0x9d, 0x74, 0x57, 0x5b, 0xab, 0x48, 0x21, 0x20, 0x35, 0x8a,
	0x38, 0xf4, 0xe4, 0x48, 0xbb, 0xe2, 0x52, 0x6e, 0x94, 0x0a, 0x71, 0xe1, 0x10, 0xe0, 0x02, 0x87,
	0x2a, 0x8d, 0xa7, 0x95, 0xa5, 0xd4, 0x0e, 0xb1, 0xb7, 0x1c, 0x79, 0x0f, 0x5e, 0x93, 0x17, 0x40,
	0xfe, 0x93, 0xed, 0x7a, 0x39, 0x2c, 0x5c, 0x7a, 0x49, 0xe4, 0xf1, 0xfc, 0x3e, 0x7b, 0xc6, 0xdf,
	0xc0, 0x8b, 0xae, 0x97, 0x5a, 0x96, 0x97, 0x75, 0x8b, 0x82, 0xd5, 0xfd, 0x27, 0xec, 0x1f, 0x78,
	0x83, 0xd4, 0x46, 0x49, 0x8c, 0x0f, 0x28, 0x74, 0x76, 0x76, 0x27, 0xe5, 0x5d, 0x8b, 0xa5, 0x0d,
	0xde, 0xac, 0x6f, 0x4b, 0xcd, 0xef, 0x51, 0xe9, 0xfa, 0xbe, 0x73, 0x79, 0xc5, 0x0a, 0x66, 0x97,
	0x3d, 0xd6, 0x1a, 0x2b, 0xfc, 0xbe, 0x46, 0xa5, 0x49, 0x01, 0x0e, 0x4d, 0xa3, 0x3c, 0x3a, 0x4f,
	0x96, 0xc7, 0xd4, 0xae, 0xe8, 0x95, 0xf9, 0x56, 0x6e, 0xab, 0xc8, 0x61, 0x3e, 0x40, 0xaa, 0x93,
	0x42, 0x21, 0x99, 0xc3, 0x88, 0x33, 0x8b, 0x1c, 0x55, 0x23, 0xce, 0x8c, 0xec, 0x97, 0x8e, 0xfd,
	0xa7, 0xec, 0x02, 0xe6, 0x03, 0xe4, 0x64, 0x8b, 0x33, 0x98, 0xbd, 0xc3, 0x16, 0x1f, 0x65, 0x76,
	0xcf, 0x59, 0xc0, 0x7c, 0x48, 0xf0, 0xc8, 0x37, 0x48, 0x2a, 0xac, 0xd9, 0x00, 0x50, 0x38, 0x34,
	0x8a, 0xfe, 0xd8, 0x8c, 0xba, 0x7e, 0xd0, 0xa1, 0x1f, 0xf4, 0xf3, 0xd0, 0x8f, 0xca, 0xe6, 0x91,
	0x97, 0x70, 0xd4, 0x48, 0xc1, 0xb8, 0xe6, 0x52, 0xa4, 0xa3, 0x3c, 0x3a, 0x8f, 0xab, 0xc7, 0x40,
	0xb1, 0x04, 0x70, 0xe2, 0x6a, 0xdd, 0x6a, 0xf2, 0x0a, 0xc6, 0xf6, 0xe2, 0x2a, 0x8d, 0xf2, 0x83,
	0xbf, 0x8a, 0xf2, 0x7b, 0xc5, 0xaf, 0x11, 0xc4, 0x36, 0xb2, 0x7b, 0x79, 0xf2, 0x1c, 0xa6, 0xf2,
	0x87, 0xc0, 0xfe, 0x9a, 0x33, 0x7f, 0xd4, 0xc4, 0xae, 0x3f, 0x30, 0x72, 0x0a, 0xb1, 0xe6, 0xba,
	0xc5, 0xf4, 0xc0, 0x66, 0xbb, 0xc5, 0xa6, 0x98, 0xc3, 0x7f, 0x2c, 0xe6, 0x35, 0x4c, 0xcd, 0xff,
	0x1a, 0x05, 0x4b, 0xe3, 0xbd, 0xcc, 0xc4, 0xe4, 0x5e, 0x09, 0x46, 0xde, 0xc3, 0x89, 0xc5, 0x84,
	0xd4, 0xfc, 0x96, 0x37, 0xb5, 0xed, 0xc5, 0x78, 0x2f, 0xbf, 0x30, 0xd0, 0xc7, 0x2d, 0x86, 0xe4,
	0x90, 0x30, 0x54, 0x4d, 0xcf, 0x3b, 0x2b, 0x31, 0xb1, 0xb5, 0x6c, 0x87, 0x8a, 0x9f, 0x70, 0x1c,
	0x10, 0x4f, 0xdd, 0xa2, 0xe5, 0xef, 0x08, 0xa6, 0xc3, 0x04, 0x91, 0x0b, 0x48, 0x9c, 0xaf, 0xdd,
	0x7b, 0x9d, 0xfa, 0xf7, 0x0c, 0x06, 0x24, 0x7b, 0xb6, 0x13, 0xf5, 0x13, 0x70, 0x01, 0x89, 0x33,
	0x6f, 0xc8, 0x06, 0x53, 0xb0, 0x61, 0x43, 0x9b, 0x1b, 0xd6, 0xb9, 0x38, 0x64, 0x03, 0xeb, 0x6f,
	0xd8, 0xd0, 0xef, 0x64, 0xe5, 0x2c, 0x69, 0x49, 0x45, 0x88, 0x4f, 0xda, 0x1a, 0x81, 0xec, 0x24,
	0x88, 0x19, 0xe7, 0xbe, 0x9d, 0x7d, 0x4d, 0x68, 0xf9, 0xa6, 0xf1, 0x75, 0xdf, 0x8c, 0x6d, 0x7b,
	0x56, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x35, 0x59, 0xcd, 0x0d, 0x52, 0x04, 0x00, 0x00,
}
